---
- name: Hardening SSH for Ubuntu 22.04 LTS
  hosts: user
  become: true
  tasks:

    - name: Remove SSH host keys
      file:
        path: "/etc/ssh/{{ item }}"
        state: absent
      loop:
        - ssh_host_rsa_key
        - ssh_host_rsa_key.pub
        - ssh_host_ed25519_key
        - ssh_host_ed25519_key.pub

    - name: Generate new SSH host keys
      command: "{{ item }}"
      loop:
        - "ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''"
        - "ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''"
    
    - name: Remove Diffie-Hellman modules with less 3071 bit
      shell: "awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe && mv /etc/ssh/moduli.safe /etc/ssh/moduli"
      args:
        executable: /bin/bash

    - name: Add the new SSH host keys in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{ item }}"
        create: yes
      loop:
        - "HostKey /etc/ssh/ssh_host_rsa_key"
        - "HostKey /etc/ssh/ssh_host_ed25519_key"

    - name: Configure secure encryption and MAC algorithms 
      copy:
        dest: /etc/ssh/sshd_config.d/ssh-audit_hardening.conf
        content: |
          # SSH Hardening basato su sshaudit.com
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
          Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
          MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
          HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com
    
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
